#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: uSjN60Ag6PE3mFlODR7z
#            client-secret: XxbGt7LJ_l
#            client-name: Naver
#            redirect-uri: "{http://catchplan-env.eba-ngqypwbe.ap-northeast-2.elasticbeanstalk.com}/login/oauth2/code/{hdn1015}"
#
##            redirect-uri: "{http://localhost:8080}/login/oauth2/code/{hdn1015}"
#            scope:
#              - profile_name
#              - prifile_nickname
#              - phone_number
 spring:

   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://awseb-e-iqft7xjffq-stack-awsebrdsdatabase-k5jzrhqspslx.cmsm8zjdzvh7.ap-northeast-2.rds.amazonaws.com:3306/beanstalk?serverTimezone=Asia/Seoul
     username: sunneng
     password: llgy88388!

   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         format_sql: true
         show_sql: true
 logging:
   level:
     com.tutorial: debug

 token:
   secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
   access-token-expiration-time: 900000
   refresh-token-expiration-time: 1209600000

   remote:
     server:
       url: http://catchplan-env.eba-ngqypwbe.ap-northeast-2.elasticbeanstalk.com

 springdoc:
   version: v1
   packages-to-scan: mycatchplan.mycatchplan
   default-consumes-media-type: application/json;charset=UTF-8
   default-produces-media-type: application/json;charset=UTF-8
   swagger-ui:
     path: swagger-ui.html            # Swagger UI 경로 => localhost:8081/swagger-ui.html
     tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
     operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
     doc-expansion: none
   api-docs:
     path: /api-docs/json
     groups:
       enabled: true
   cache:
     disabled: true



#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: uSjN60Ag6PE3mFlODR7z
#            client-secret: XxbGt7LJ_l
#            client-name: Naver
#            redirect-uri: "{http://catchplan-env.eba-ngqypwbe.ap-northeast-2.elasticbeanstalk.com}/login/oauth2/code/{hdn1015}"
#
##            redirect-uri: "{http://localhost:8080}/login/oauth2/code/{hdn1015}"
#            scope:
#              - profile_name
#              - prifile_nickname
#              - phone_number
#spring:
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://awseb-e-iqft7xjffq-stack-awsebrdsdatabase-k5jzrhqspslx.cmsm8zjdzvh7.ap-northeast-2.rds.amazonaws.com:3306/beanstalk?serverTimezone=Asia/Seoul
#    username: sunneng
#    password: llgy88388!
#  #
#  #  datasource:
#  #    url: jdbc:h2:tcp://localhost/~/team1
#  #    username: sa
#  #    password:
#  #    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#logging:
#  level:
#    com.tutorial: debug
#
#
#token:
#  secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
#  access-token-expiration-time: 900000
#  refresh-token-expiration-time: 1209600000
#
#  remote:
#    server:
#      url: http://catchplan-env.eba-ngqypwbe.ap-northeast-2.elasticbeanstalk.com
#
##springdoc:
##  api-docs:
##    path: /swagger-ui.html
#
#
#springdoc:
#  version: v1
#  packages-to-scan: mycatchplan.mycatchplan
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: swagger-ui.html            # Swagger UI 경로 => localhost:8081/swagger-ui.html
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    doc-expansion: none
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true
