spring:
  cloud:
    aws:
      s3:
        bucket: catchplanbucket
      credentials:
        access-key: AKIAVDQOA2F7SGUIGN7H
        secret-key: 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
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
#    username: root
#    password: tkfkdgkf123!

#   서버올릴땐 밑에 걸로
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: llgy88388!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    com.tutorial: debug


token:
  secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
  access-token-expiration-time: 1209600000
  refresh-token-expiration-time: 63200000000

  remote:
    server:
      url: http://catchplan-env.eba-ngqypwbe.ap-northeast-2.elasticbeanstalk.com


springdoc:
  api-docs:
    path: /swagger-ui.html