
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul  #본인에 맞는 local db url 설정 하기
    username: root
    password: llgy88388!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    com.tutorial: debug


token:
  secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
  access-token-expiration-time: 1209600000
  refresh-token-expiration-time: 63200000000

  remote:
    server:
      url: http://catchplan-env.eba-ngqypwbe.ap-northeast-2.elasticbeanstalk.com

springdoc:
  api-docs:
    path: /swagger-ui.html


