spring:
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: ${rds.driver}

  cloud:
    aws:
      s3:
        bucket: catchplan
      credentials:
        access-key: AKIAVDQOA2F7XHDB7T4R
        secret-key: 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
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false

  jpa:
    hibernate:
      ddl-auto: update
    # application 실행 시점에 기존에 갖고 있던 테이블을 다 지우고 다시 생성합니다.
    properties:
      hibernate:
        #        show_sql: true
        # 모든 로그는 가급적 로거를 통해 남겨야 합니다. show_sql의 경우 System.out에 hibernate 실행 sql을 남기므로, org.hibernate.SQL 옵션을 통해 logger로 실행 SQL을 남기는 게 좋습니다.
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# 로거를 통해 로그 남기려면 org.hibernate.SQL을 사용합니다.
#  org.hibernate.type: trace
# trace로 hibernate type을 지정함으로써 로그에 SQL 실행 파라미터를 표시할 수 있습니다.

server:
  port: 5000

